### ISSUE TITLE
Apt repository not correct for elasticsearch / ubuntu 14.04

### ISSUE THREAD

**Issue by wstaples** [vkhatri/chef-elasticsearch-cluster#75]
### Expected behavior

I was expecting the package `elasticsearch` to be installed.
### Actual behavior

the file `/etc/apt/sources.list.d/elasticsearch.list` contains an incorrect apt repository. When manually running apt the package `elasticsearch` is not available at any version. There are error messages when running apt-get update. 
### WorkAround
1. edit the file `/etc/apt/sources.list.d/elasticsearch.list`  
   change `deb      "http://packages.elastic.co/elasticsearch/2.x/debian" trusty stable main`  
   to `deb      "http://packages.elastic.co/elasticsearch/2.x/debian" stable main` (remove the word trusty)  
2. Manually install the package `apt-get install elasticsearch`
3. set the attribute default['elasticsearch']['version'] to whatever version was installed
4. when the cookbook is re-run the apt source list will be broken again however it will not try to reinstall and the cookbook will move on 
### Steps to reproduce
1. create empty cookbook
2. set the attribute default['elasticsearch']['config']['cluster.name'] somewhere. 
3. add `include_recipe elasticsearch-cluster::default` to the default recipe of the wrapper cookbook 
4. run `kitchen converge`
### Cookbook Version

`0.5.3`
### Host operating system

Ubuntu 14.04 (inside vagrant/virtualbox)
### Berksfile

``` ruby
cookbook 'elasticsearch-cluster', '~> 0.5.3'
cookbook 'kibana', '~> 0.1.10'
```
### My Recipe

``` ruby
# setup elastic search
include_recipe "elasticsearch-cluster::default"
```
### Error

```
          Hit http://ppa.launchpad.net trusty/main Translation-en
             Err http://packages.elastic.co trusty/stable amd64 Packages
        404  Not Found [IP: 184.72.244.137 80]
             Err http://packages.elastic.co trusty/main amd64 Packages
        404  Not Found [IP: 184.72.244.137 80]
             Err http://packages.elastic.co trusty/stable i386 Packages
        404  Not Found [IP: 184.72.244.137 80]
             Err http://packages.elastic.co trusty/main i386 Packages
        404  Not Found [IP: 184.72.244.137 80]
             Ign http://packages.elastic.co trusty/main Translation-en
             Ign http://packages.elastic.co trusty/stable Translation-en
             STDERR: W: Failed to fetch http://packages.elastic.co/elasticsearch/2.x/debian/dists/trusty/stable/binary-amd64/Packages  404  Not Found [IP: 184.72.244.137 80]

             W: Failed to fetch http://packages.elastic.co/elasticsearch/2.x/debian/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 184.72.244.137 80]

             W: Failed to fetch http://packages.elastic.co/elasticsearch/2.x/debian/dists/trusty/stable/binary-i386/Packages  404  Not Found [IP: 184.72.244.137 80]

             W: Failed to fetch http://packages.elastic.co/elasticsearch/2.x/debian/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 184.72.244.137 80]

             E: Some index files failed to download. They have been ignored, or old ones used instead.
             ---- End output of apt-get -q update ----
             Ran apt-get -q update returned 100

             Resource Declaration:
             ---------------------
             # In /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/apt_repository.rb

       57:         declare_resource(:apt_update, new_resource.name) do
       58:           ignore_failure true
       59:           action :nothing
       60:         end
       61:

             Compiled Resource:
             ------------------
             # Declared in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/apt_repository.rb:57:in `block in <class:AptRepository>'

             apt_update("elasticsearch") do
        action [:nothing]
        ignore_failure true
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :apt_update
        cookbook_name :"elasticsearch-cluster"
             end

             Platform:
             ---------
             x86_64-linux


 * apt_package[elasticsearch] action install
           * No candidate version available for elasticsearch
           ================================================================================
           Error executing action `install` on resource 'apt_package[elasticsearch]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for elasticsearch

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/elasticsearch-cluster/recipes/package.rb

            43: package 'elasticsearch' do
            44:   version node['elasticsearch']['version'] + node['elasticsearch']['version_suffix']
            45: end
            46:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/elasticsearch-cluster/recipes/package.rb:43:in `from_file'

           apt_package("elasticsearch") do
             package_name "elasticsearch"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name :"elasticsearch-cluster"
             recipe_name "package"
             version "2.1.1"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by vkhatri** [comment]
@wstaples Fixed, thank you for reporting. 👍

**Comment by vkhatri** [comment]
Closing.
